version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/arommers/data/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/arommers/data/wordpress
      o: bind
